name: Update Bogon Lists

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Download latest bogon lists
        run: python update_bogons.py
      
      - name: Check for changes or new files
        id: check_changes
        run: |
          if [ ! -f bogons_ipv4.txt ] || [ ! -f bogons_ipv6.txt ] || ! git diff --quiet; then
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push if changed or new
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add bogons_ipv4.txt bogons_ipv6.txt
          git commit -m "Update bogon lists [skip ci]"
          git push 
